[package]
name = "vanilla_text"
version = "0.1.0"
authors = ["Koji Matsumoto <otomustam.ijok@gmail.com>, tipeter <piotr.tihanyi@gmail.com>"]
edition = "2018"

[dependencies]
gio = "0.5.1"
gdk = "0.9.0"
gdk-pixbuf = "0.5.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_22"]

